export const popularBookGenres = [
  { key: "allGenres", label: "All Genres" },
  { key: "fiction", label: "Fiction" },
  { key: "biographyAutobiography", label: "Biography & Autobiography" },
  { key: "selfHelp", label: "Self-Help" },
  { key: "businessEconomics", label: "Business & Economics" },
  { key: "healthFitness", label: "Health & Fitness" },
  { key: "science", label: "Science" },
  { key: "history", label: "History" },
  { key: "religion", label: "Religion" },
  { key: "psychology", label: "Psychology" },
  { key: "youngAdultFiction", label: "Young Adult Fiction" },
  { key: "juvenileFiction", label: "Juvenile Fiction" },
  { key: "computers", label: "Computers" },
  { key: "cooking", label: "Cooking" },
  { key: "travel", label: "Travel" },
  { key: "trueCrime", label: "True Crime" },
  { key: "romance", label: "Romance" },
  { key: "mysteryDetective", label: "Mystery & Detective" },
  { key: "fantasy", label: "Fantasy" },
  { key: "graphicNovels", label: "Graphic Novels" },
  { key: "artPhotography", label: "Art & Photography" },
  { key: "comics", label: "Comics & Graphic Novels" },
  { key: "outdoor", label: "Kennebec River Valley (Me.)" },
  { key: "art", label: "Art" },
];
