export const popularBookGenres = [
  "All Genres",
  "Fiction",
  "Biography & Autobiography",
  "Self-Help",
  "Business & Economics",
  "Health & Fitness",
  "Science",
  "History",
  "Religion",
  "Psychology",
  "Young Adult Fiction",
  "Juvenile Fiction",
  "Computers",
  "Cooking",
  "Travel",
  "True Crime",
  "Romance",
  "Mystery & Detective",
  "Fantasy",
  "Graphic Novels",
  "Art & Photography",
];
